/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 02 15:27:19 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.CharBuffer;
import org.apache.commons.lang3.text.translate.OctalUnescaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OctalUnescaper_ESTest extends OctalUnescaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) null);
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      int int0 = octalUnescaper0.translate((CharSequence) stringBuffer0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[6];
      charArray0[1] = '\\';
      charArray0[2] = '7';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      String string0 = octalUnescaper0.translate((CharSequence) charBuffer0);
      assertEquals("\u0000\u0007\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter('\\');
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) "-\\\\", (int) '\\', (Writer) stringWriter0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[7];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter('5');
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) charBuffer0, (int) '5', (Writer) stringWriter0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[7];
      charArray0[0] = '\\';
      charArray0[1] = '5';
      charArray0[2] = '5';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter('\\');
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals("-", stringWriter0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[7];
      charArray0[0] = '\\';
      charArray0[1] = '0';
      charArray0[2] = '0';
      charArray0[3] = '0';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals("\u0000", stringWriter0.toString());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[4];
      charArray0[1] = '\\';
      charArray0[2] = '0';
      charArray0[3] = '0';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter(1);
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0000", stringWriter0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[3];
      charArray0[1] = '\\';
      charArray0[2] = '5';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.OctalUnescaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[6];
      charArray0[0] = '\\';
      charArray0[1] = '3';
      charArray0[2] = '3';
      charArray0[3] = '3';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      String string0 = octalUnescaper0.translate((CharSequence) charBuffer0);
      assertEquals("\u00DB\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[7];
      charArray0[6] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      String string0 = octalUnescaper0.translate((CharSequence) charBuffer0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000\u0000\\", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[7];
      charArray0[0] = '\\';
      charArray0[1] = '0';
      charArray0[2] = '0';
      charArray0[3] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append('\\');
      StringWriter stringWriter2 = stringWriter1.append((CharSequence) charBuffer0);
      StringBuffer stringBuffer0 = stringWriter2.getBuffer();
      int int0 = octalUnescaper0.translate((CharSequence) stringBuffer0, 1, (Writer) stringWriter1);
      assertEquals("\\\\00\\\u0000\u0000\u0000\u0000", stringBuffer0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[4];
      charArray0[0] = '\\';
      charArray0[1] = '0';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      stringWriter0.append((CharSequence) charBuffer0);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      int int0 = octalUnescaper0.translate((CharSequence) stringBuffer0, 0, (Writer) stringWriter0);
      assertEquals("\\0\u0000\u0000\u0000", stringBuffer0.toString());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[4];
      charArray0[0] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      stringWriter0.append((CharSequence) charBuffer0);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      int int0 = octalUnescaper0.translate((CharSequence) stringBuffer0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }
}
