/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 02 15:37:55 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.text.translate.JavaUnicodeEscaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JavaUnicodeEscaper_ESTest extends JavaUnicodeEscaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.below((-2907));
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape((-2907));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.Character", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = new JavaUnicodeEscaper(2293, 2293, true);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.above(103);
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.between(103, 103);
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape(103);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.apache.commons.lang3.text.translate.JavaUnicodeEscaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.outsideOf(1159, 0);
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.between((-3469), 54);
      assertNotNull(javaUnicodeEscaper0);
  }
}
