/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 02 15:31:51 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.CharBuffer;
import org.apache.commons.lang3.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[4];
      CharBuffer charBuffer0 = CharBuffer.allocate(2484);
      charSequenceArray0[0] = (CharSequence) charBuffer0;
      charSequenceArray0[1] = (CharSequence) "6";
      CharBuffer charBuffer1 = CharBuffer.allocate(6);
      CharSequence[][] charSequenceArray1 = new CharSequence[8][8];
      charSequenceArray1[0] = charSequenceArray0;
      charSequenceArray1[1] = charSequenceArray0;
      CharSequence[] charSequenceArray2 = new CharSequence[2];
      charSequenceArray2[0] = (CharSequence) charBuffer1;
      charSequenceArray2[1] = (CharSequence) charBuffer1;
      charSequenceArray1[2] = charSequenceArray2;
      charSequenceArray1[3] = charSequenceArray0;
      charSequenceArray1[4] = charSequenceArray0;
      charSequenceArray1[5] = charSequenceArray0;
      charSequenceArray1[6] = charSequenceArray0;
      charSequenceArray1[7] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
      StringWriter stringWriter0 = new StringWriter();
      int int0 = lookupTranslator0.translate((CharSequence) charBuffer0, 6, (Writer) stringWriter0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000\u0000", stringWriter0.toString());
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][0];
      CharSequence[] charSequenceArray1 = new CharSequence[4];
      CharBuffer charBuffer0 = CharBuffer.allocate(2484);
      charSequenceArray1[0] = (CharSequence) charBuffer0;
      charSequenceArray1[1] = (CharSequence) "6";
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      CharBuffer charBuffer1 = CharBuffer.allocate(2509);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) charBuffer1, 0, (Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][2];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) stringBuffer0, (-865), (Writer) stringWriter0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 0, 0);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[2][6];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      charSequenceArray1[0] = (CharSequence) stringBuffer0;
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0, 0, 0);
      charSequenceArray1[1] = (CharSequence) charBuffer0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[6];
      CharBuffer charBuffer0 = CharBuffer.allocate(539);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 539, 539);
      charSequenceArray0[0] = (CharSequence) charBuffer1;
      charSequenceArray0[1] = (CharSequence) charBuffer1;
      CharSequence[][] charSequenceArray1 = new CharSequence[5][5];
      charSequenceArray1[0] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // 539
         //
         verifyException("java.nio.StringCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[3][3];
      CharSequence[] charSequenceArray1 = new CharSequence[1];
      charSequenceArray1[0] = (CharSequence) "7";
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[3][7];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      charSequenceArray1[0] = (CharSequence) "0";
      CharBuffer charBuffer0 = CharBuffer.wrap(charSequenceArray1[0]);
      charSequenceArray1[1] = (CharSequence) charBuffer0;
      charSequenceArray0[0] = charSequenceArray1;
      charSequenceArray0[1] = charSequenceArray1;
      charSequenceArray0[2] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter();
      int int0 = lookupTranslator0.translate(charSequenceArray1[1], 0, (Writer) stringWriter0);
      assertEquals("0", stringWriter0.toString());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][0];
      CharSequence[] charSequenceArray1 = new CharSequence[4];
      CharBuffer charBuffer0 = CharBuffer.allocate(2484);
      charSequenceArray1[0] = (CharSequence) charBuffer0;
      charSequenceArray1[1] = (CharSequence) "9B4";
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      int int0 = lookupTranslator0.translate(charSequenceArray1[0], 18, (Writer) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][0];
      CharSequence[] charSequenceArray1 = new CharSequence[4];
      CharBuffer charBuffer0 = CharBuffer.allocate(2484);
      charSequenceArray1[0] = (CharSequence) charBuffer0;
      charSequenceArray1[1] = (CharSequence) "9B4";
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      String string0 = lookupTranslator0.translate((CharSequence) "9B4");
      assertEquals("9B4", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[8][8];
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
      StringWriter stringWriter0 = new StringWriter();
      CharBuffer charBuffer0 = CharBuffer.allocate(1350);
      int int0 = lookupTranslator0.translate((CharSequence) charBuffer0, (int) 'F', (Writer) stringWriter0);
      assertEquals(0, int0);
  }
}
